spring.application.name=Authifyy
server.port=8081

# Hardcoded PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://pgcloud_p3sb_user:qnKQW3V8iScEYJzARB83PagqzxNtwBhh@dpg-d73p1c75r7bs73chqqvg-a/pgcloud_p3sb?sslmode=require
spring.datasource.username=pgcloud_p3sb_user
spring.datasource.password=qnKQW3V8iScEYJzARB83PagqzxNtwBhh

# Hibernate dialect for PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# JWT and Context Path
jwt.secret.key=thisisthesecretekeyievercreatedinmydevelopmentcareer
server.servlet.context-path=/api/v1.0

# Mail settings
spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=8e7ad3001@smtp-brevo.com
spring.mail.password=9KVfFv2Cg0QwRAXd
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.from=himanshukumar93079@gmail.com
