spring.application.name=Authifyy
server.port=8081

# 1. Remove credentials from the URL string
spring.datasource.url=jdbc:postgresql://dpg-d73p1c75r7bs73chqqvg-a:5432/pgcloud_p3sb?sslmode=require
spring.datasource.username=pgcloud_p3sb_user
spring.datasource.password=qnKQW3V8iScEYJzARB83PagqzxNtwBhh

# 3. Ensure the driver can be found (Hibernate 6+ usually handles this automatically)
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate dialect for PostgreSQL
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# JWT and Context Path
jwt.secret.key=thisisthesecretekeyievercreatedinmydevelopmentcareer
server.servlet.context-path=/api/v1.0

spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=8e7ad3001@smtp-brevo.com
spring.mail.password=9KVfFv2Cg0QwRAXd
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.from=himanshukumar93079@gmail.com
